name: Build offline ECAD‑Viewer image      # 可选：工作流名称

# 1️⃣ 触发条件 —— 最常用的两种：
#    • workflow_dispatch: 手动点击按钮触发
#    • schedule:        定时打包（示例：每周日凌晨 2 点 UTC）
on:
  workflow_dispatch:           # 手动触发
  schedule:
    - cron: '0 2 * * 0'        # (可选) 每周日 02:00 UTC

# 2️⃣ 工作任务
jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4            # 拉取仓库代码，上传 Artifact 时需要

      # 如镜像是私有的，先登录 GHCR（需要设置 GHCR_PAT 机密）
      - name: Log in to GHCR
        if: ${{ secrets.GHCR_PAT != '' }}    # 公共镜像可删掉这一步
        run: |
          echo "${{ secrets.GHCR_PAT }}" | \
            docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull image
        run: |
          docker pull ghcr.io/huaqiu-electronics/ecad-viewer:full

      - name: Save & compress as tar.gz
        run: |
          docker save ghcr.io/huaqiu-electronics/ecad-viewer:full \
            | gzip -c > ecad-viewer_full.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ecad-viewer-offline
          path: ecad-viewer_full.tar.gz
